Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    # Forward the port 80 to 8080
    config.vm.network "forwarded_port", guest:80, host:8080
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
    
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 2
  
    end
  
    # configure a web server inside VM
  
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx
    SHELL
  
  end
  