Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["numvcpus"] = "2"
    vmware.vmx["memsize"] = "2048"
    vmware.vmx["displayname"] = "test"
    vmware.gui = true 
  end
end




