BASE_BOX_IMAGE = "ubuntu/jammy64"
CPUS_CONTROLLER = 2
MEMORY_CONTROLLER = 4096
CPUS_COMPUTE = 2
MEMORY_COMPUTE = 2048
# Change to increase the number of COMPUTEs
COMPUTE_NODE_COUNT = 1

Vagrant.configure("2") do |config|
  # config.vm.provision "shell", path: "common.sh"
  # CONTROLLER node

  config.vm.define "controller" do |controller|
    controller.vm.box = BASE_BOX_IMAGE
    controller.vm.hostname = "controller.example.com"
    controller.vm.network "private_network", ip: "192.168.56.254"
    master.vm.network "forwarded_port", guest: 5000, host: 5000
    controller.vm.provider "virtualbox" do |vb|
      vb.name = "controller"
      vb.cpus = CPUS_CONTROLLER
      vb.memory = MEMORY_CONTROLLER
    end

    # controller.vm.provision "shell", path: "controller.sh"
  end

    # COMPUTE node

    (1..COMPUTE_NODE_COUNT).each do |i|
      config.vm.define "compute#{i}" do |compute|
        compute.vm.box = BASE_BOX_IMAGE
        compute.vm.hostname = "compute#{i}.example.com"
        compute.vm.network "private_network", ip: "192.168.56.10#{i}"
        compute.vm.provider "virtualbox" do |vb|
          vb.name = "compute#{i}"
          vb.cpus = CPUS_COMPUTE
          vb.memory = MEMORY_COMPUTE
        end
        # compute.vm.provision "shell", path: "compute.sh"
      end
  end
end
