VAGRANT_API_VERSION  = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = "webserver"
    # Forward the port 80 to 8080
    web.vm.network "forwarded_port", guest:80, host:8080
    web.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 1
    end
        # configure a web server inside VM

        web.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y nginx
      SHELL
  
  end


    config.vm.define "db" do |db|
      db.vm.box = "ubuntu/trusty64"
      db.vm.hostname = "dbserver"
      # Forward the port 3306 to 3306
      db.vm.network "forwarded_port", guest:3306, host:3306
      db.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
        vb.cpus = 1
      end

    db.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y mysql-server
  SHELL

    end
  



end
